### ISSUE TITLE
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by kingking888** [m0bilesecurity/RMS-Runtime-Mobile-Security#15]
[2020-05-17 19:08:55,328] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "D:\microsoft\python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\microsoft\python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\microsoft\python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\microsoft\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\microsoft\python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\microsoft\python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:/PyhonProject/venv/Projects/fridahook/RMS-Runtime-Mobile-Security/mobilesecurity.py", line 168, in device_management
    session = device.attach(config["system_package"])
  File "D:\microsoft\python37\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "D:\microsoft\python37\lib\site-packages\frida\core.py", line 156, in attach
    return Session(self._impl.attach(self._pid_of(target)))
  File "D:\microsoft\python37\lib\site-packages\frida\core.py", line 180, in _pid_of
    return self.get_process(target).pid
  File "D:\microsoft\python37\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "D:\microsoft\python37\lib\site-packages\frida\core.py", line 106, in get_process
    matching = [process for process in self._impl.enumerate_processes() if fnmatch.fnmatchcase(process.name.lower(), process_name_lc)]
frida.ServerNotRunningError: unable to connect to remote frida-server: closed
127.0.0.1 - - [17/May/2020 19:08:55] "POST / HTTP/1.1" 500 -

**Comment by m0bilesecurity** [comment]
Is frida-server up and running on the target device?
More info here: https://frida.re/docs/android/

**Comment by kingking888** [comment]
Yeah  ,  it's OK  now ,  full thanks!

**Comment by kingking888** [comment]
Yeah  ,  it's OK  now ,  full thanks!
