### ISSUE TITLE
Installation issue via npm when isntalling frida

### ISSUE THREAD

**Issue by hustwyk** [m0bilesecurity/RMS-Runtime-Mobile-Security#63]
**Having issues when installing via npm**
It seems like a problem when installing frida.
I've tried Development mode but returned the same result.
I've googled it and tried with `-no-strict-ssl --unsafe` parameters but it's useless.
Now I have no idea, could anyone help?

**To Reproduce**

```
npm install -g rms-runtime-mobile-security
```
See errors below

**Desktop (please complete the following information):**

OS: Ubuntu 16.04.7 LTS
Node: v14.16.0
Console Logs

```
$ npm install -g rms-runtime-mobile-security
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/.../node-v14.16.0-linux-x64/bin/RMS-Runtime-Mobile-Security -> /.../node-v14.16.0-linux-x64/lib/node_modules/rms-runtime-mobile-security/rms.js
/.../node-v14.16.0-linux-x64/bin/rms -> /.../node-v14.16.0-linux-x64/lib/node_modules/rms-runtime-mobile-security/rms.js

> frida@14.2.13 install /.../node-v14.16.0-linux-x64/lib/node_modules/rms-runtime-mobile-security/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install unable to verify the first certificate
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:932:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
gyp ERR! System Linux 4.15.0-132-generic
gyp ERR! command "/.../node-v14.16.0-linux-x64/bin/node" "/.../node-v14.16.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /.../node-v14.16.0-linux-x64/lib/node_modules/rms-runtime-mobile-security/node_modules/frida
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/rms-runtime-mobile-security/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@14.2.13 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frida@14.2.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by m0bilesecurity** [comment]
Hey @hustwyk  
please read some possible solutions here #50 and here #51
Thanks
