### ISSUE TITLE
Unable to start RMS

### ISSUE THREAD

**Issue by kaleb-g** [m0bilesecurity/RMS-Runtime-Mobile-Security#89]
**Unable to start the RMS** [Required]
I installed the it using the said instructions, but when I try to run it, it says "address already in use" Even tho there's no service running on that port.

1. Run the "rms" on the terminal
2. Error Will show

```
rms
events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/rms-runtime-mobile-security/rms.js:91:8)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 5000
}
```

Macbook Air M1 version 12.1

**Comment by Derewith** [comment]
`EADDRINUSE` have you checked what's going on with the port 5000? @kaleb-g

**Comment by jauharbal** [comment]
I got the same error, and it seems the other process running on the same port, I'm wondering if we have an option to customise the port in RMS
@Derewith

**Comment by m0bilesecurity** [comment]
@jauharbal sure, just edit this line with a different port 😉
https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/blob/0e655ace33278911662864e375f16995b6f6b080/rms.js#L91

**Comment by jauharbal** [comment]
> @jauharbal sure, just edit this line with a different port 😉
> 
> https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/blob/0e655ace33278911662864e375f16995b6f6b080/rms.js#L91

Thanks @m0bilesecurity !! I found this however encountered other npm based issues, will try again.

**Comment by Tony-Y** [comment]
Disable AirPlay receiver. HOWTO: https://paretosecurity.com/auditor/checks/airplay
