### ISSUE TITLE
 When loading a script, an error occurs if the script is long.

### ISSUE THREAD

**Issue by daeinlee** [m0bilesecurity/RMS-Runtime-Mobile-Security#91]
Hello. Thanks for making such a great tool.
In AOS, when the load script is long, an error occurs.
아래는 에러 메세지입니다.

------------------------------------------
PayloadTooLargeError: request entity too large
    at readStream (F:\rms\RMS-Runtime-Mobile-Security-master\node_modules\raw-body\index.js:155:17)
    at getRawBody (F:\rms\RMS-Runtime-Mobile-Security-master\node_modules\raw-body\index.js:108:12)
    at read (F:\rms\RMS-Runtime-Mobile-Security-master\node_modules\body-parser\lib\read.js:77:3)
    at urlencodedParser (F:\rms\RMS-Runtime-Mobile-Security-master\node_modules\body-parser\lib\types\urlencoded.js:116:5)
    at Layer.handle [as handle_request] (F:\rms\RMS-Runtime-Mobile-Security-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (F:\rms\RMS-Runtime-Mobile-Security-master\node_modules\express\lib\router\index.js:317:13)
    at F:\rms\RMS-Runtime-Mobile-Security-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (F:\rms\RMS-Runtime-Mobile-Security-master\node_modules\express\lib\router\index.js:335:12)
    at next (F:\rms\RMS-Runtime-Mobile-Security-master\node_modules\express\lib\router\index.js:275:10)
    at expressInit (F:\rms\RMS-Runtime-Mobile-Security-master\node_modules\express\lib\middleware\init.js:40:5)

**Comment by m0bilesecurity** [comment]
Ciao @daeinlee,
is the same script working via the frida cli?

**Comment by daeinlee** [comment]
> Ciao @daeinlee, is the same script working via the frida cli?

Yep. The script works fine. 
The script tested is the il2cpp dump script obtained from the frida il2cpp bridge.
The script is very long.

**Comment by m0bilesecurity** [comment]
Hey @daeinlee can you kindly try again with the new RMS version (1.5.12)?

**Comment by daeinlee** [comment]
Thank you for caring me. It seems to be difficult right now, but I will test it later and tell you if there is anything wrong.

**Comment by Numenorean** [comment]
@m0bilesecurity not fixed, last version (1.5.14). The script is ~1850 lines long
